<!-- main section start -->
<main>

<section class="px-5 md:px-10 lg:px-0 lg:w-10/12 mx-auto mt-4" style="padding-bottom:50px">
    <h1 class="text-xl lg:text-3xl font-semibold">What is blood donation?</h1>
    <p class="mt-8 font-medium text-sm lg:text-base">A blood donation occurs when a person voluntarily has blood drawn and used for transfusions and/or made into biopharmaceutical medications by a process called fractionation (separation of whole-blood components). Donation may be of whole blood (WB), or of specific components directly (the latter called apheresis). Blood banks often participate in the collection process as well as the procedures that follow it.</p>
    <p class="mt-5 font-medium text-sm lg:text-base">Today in the developed world, most blood donors are unpaid volunteers who donate blood for a community supply. In some countries, established supplies are limited and donors usually give blood when family or friends need a transfusion (directed donation). Many donors donate as an act of charity, but in countries that allow paid donation some donors are paid, and in some cases, there are incentives other than money such as paid time off from work. Donors can also have blood drawn for their own future use (autologous donation). Donating is relatively safe, but some donors have to bruise where the needle is inserted or may feel faint.</p>
    <p class="mt-5 font-medium text-sm lg:text-base">Potential donors are evaluated for anything that might make their blood unsafe to use. The screening includes testing for diseases that can be transmitted by a blood transfusion, including HIV and viral hepatitis. The donor must also answer questions about medical history and take a short physical examination to make sure the donation is not hazardous to his or her health. How often a donor can donate varies from days to months based on what component they donate and the laws of the country where the donation takes place. For example, in the United States, donors must wait for eight weeks (56 days) between whole blood donations but only seven days between plateletpheresis donations and twice per seven-day period in plasmapheresis.</p>
    <p class="mt-5 font-medium text-sm lg:text-base">The amount of blood drawn and the methods vary. The collection can be done manually or with automated equipment that takes only specific components of the blood. Most of the components of blood used for transfusions have a short shelf life, and maintaining a constant supply is a persistent problem. This has led to some increased interest in autotransfusion, whereby a patient’s blood is salvaged during surgery for continuous reinfusion—or alternatively, is “self-donated” prior to when it will be needed. (Generally, the notion of “donation” does not refer to giving to one’s self, though in this context it has become somewhat acceptably idiomatic.)</p>
</section>